### ISSUE TITLE
Implement an autoscroll on the leaderboard

### ISSUE THREAD

**Issue by anuragrao04** [acmpesuecc/Hacknight5.0_Leaderboard#28]
## About

On the `/leaderboard` page, there is a hero section that takes up the screen. After this, the user has to scroll down to see the leaderboard.

Please implement an autoscroll feature, where, on page load, the hero section is visible for a few seconds and then the it automatically scrolls to the leaderboard. This should happen only if there is no user interaction. If a user interaction is detected (basically a scroll), this autoscroll behaviour must be aborted. 

## Bounty 60

**Comment by Ritwik-Ag** [comment]
can u assign me this

**Comment by neethanm** [comment]
can i be assigned to this? #28

**Comment by Ritwik-Ag** [comment]
@anuragrao04 we have to write code in js or html

**Comment by Rohan123R** [comment]
@anuragrao04  CAN I PLEASE GET ASSIGNED TO THIS ?

**Comment by NishanHolla** [comment]
Can i be assigned this ?

**Comment by anuragrao04** [comment]
assigned @Ritwik-Ag

**Comment by anuragrao04** [comment]
@Rohan123R caps lock

**Comment by rithulkamesh** [comment]
Can i get assigned on this?

**Comment by NishanHolla** [comment]
i am still waiting to be assigned

**Comment by anuragrao04** [comment]
@rithulkamesh where are you

**Comment by rithulkamesh** [comment]
@anuragrao04 semhall2
working on stopping the scroll

**Comment by rithulkamesh** [comment]
#34

**Comment by anuragrao04** [comment]
@Ritwik-Ag I'm sorry but you opened your PR after @rithulkamesh started work on the issue. You were inactive for this while and it was automatically assigned to @rithulkamesh. So I cannot accept your PR

**Comment by Ritwik-Ag** [comment]
@anuragrao04 it was because of some issue in my github.

**Comment by AnshulBanda** [comment]
can i work on this issue?

**Comment by Samantha-Susan-John** [comment]
Can i be assigned to this?
